# shopee scrape variables
main_link = "https://seller.shopee.com.my/"
username = "//input[@class='pDzPRp' and @type='text']"
password = "//input[@class='pDzPRp' and @type='password']"
login = "//button[contains(text(),'Log In')]"
verify_email_otp = "//div[@class='VXfiwU']//div[@class='quvuMg']//button[@class='E62KYV']"
languagebutton = "//button[contains(text(),'English')]"
Shopee_ads = "//ul[@class='sidebar-submenu']//li//a//span[contains(text(),'Shopee Ads')]"
Shopee_ads_popup = "//div[@class='shopee-modal']//div//div//div//i"
calendar = "//div[@class='shopee-date-picker__input']//div//div//i[@class='shopee-selector__prefix-icon shopee-icon']"
alter_calendar = "//div[@class='shopee-date-picker ads-date-range-picker']//div[@class='shopee-date-picker__input']//div[@class='shopee-selector clearable shopee-selector--normal active-clearable']//div[@class='shopee-selector__prefix']"
month_navigator = "//div[@class='shopee-daterange-picker-panel']//div[@class='shopee-daterange-picker-panel__body']//div[@class='shopee-daterange-picker-panel__body-left']//div[@class='shopee-date-picker-panel__date']//div[@class='shopee-picker-header']//i[@class='shopee-icon shopee-picker-header__icon shopee-picker-header__prev']/*[name()='svg']/*[name()='path' and @d='M6.81066017,8 L10.7803301,4.03033009 C11.0732233,3.73743687 11.0732233,3.26256313 10.7803301,2.96966991 C10.4874369,2.6767767 10.0125631,2.6767767 9.71966991,2.96966991 L5.21966991,7.46966991 C4.9267767,7.76256313 4.9267767,8.23743687 5.21966991,8.53033009 L9.71966991,13.0303301 C10.0125631,13.3232233 10.4874369,13.3232233 10.7803301,13.0303301 C11.0732233,12.7374369 11.0732233,12.2625631 10.7803301,11.9696699 L6.81066017,8 Z']"
month_navigator_svg_css = ".shopee-daterange-picker-panel__body-left > div:nth-child(1) > div:nth-child(1) > i:nth-child(2) > svg:nth-child(1)"
year_navigator_svg_css = "i.shopee-picker-header__icon:nth-child(1) > svg:nth-child(1)"
year_navigator_svg_css_2 = "body > div.shopee-popper.shopee-popover__popper.shopee-popover__popper--light.bi-date-picker > div > div > div > div > div > div.shopee-picker-header > i:nth-child(1) > svg"
export_data = "//div[@class='latest']//div[@class='export shopee-dropdown']//button[@class='shopee-button shopee-button--normal']"
enterdate = "//div[@class='rc-calendar-input-wrap']//div[@class='rc-calendar-date-input-wrap']//input[@class='rc-calendar-input ']"
keyword = "//ul[@class='shopee-dropdown-menu']//li[@class='shopee-dropdown-item' and contains(text(),'Keyword/Placement Level Data')]"
keyword_popup = "//div[@class='shopee-modal__footer']//div[@class='shopee-modal__footer-buttons']//button[@class='shopee-button shopee-button--primary shopee-button--normal']"
download = "//div[@class='shopee-popover__content']//div[@class='export-container']//div[@class='list']//div[@class='list-item']//div[@class='status']//button"
business_insights = "//ul[@class='sidebar-submenu']//li//a//span[contains(text(),'Business Insights')]"
business_month_button_svg = "//div[@class='shopee-popover__ref']//div[@class='shopee-popover shopee-popover--light']//div[@class='shopee-popover__ref']//div[@class='bi-date-input track-click-open-time-selector']//div[@class='label']//i"
business_month_button_month = "//div[@class='shopee-popover__content']//div[@class='bi-date-picker__content']//ul[@class='bi-date-shortcuts shopee-date-shortcut-list with-display-text']//li//span[@class='shopee-date-shortcut-item__text' and contains(text(),'By Month')]"
business_insights_popup = "//div[@class='shopee-modal__box']//div[@class='shopee-modal__content shopee-modal__content--normal']//div[@class='shopee-modal__footer']//div[@class='shopee-modal__footer-buttons']//button//span[contains(text(),'Confirm')]"
business_insights_popup_css = "i.shopee-picker-header__icon:nth-child(1) > svg:nth-child(1)"
business_insights_popup_css_2 = "button.shopee-button--primary:nth-child(1)"
download_data = "//div[@class='fixed-time-selector']//div[@class='date-export']//button[@class='track-click-normal-export shopee-button shopee-button--normal']"
download_data_2 = "//div[@class='fixed-time-selector']//div[@class='date-export']//button//i[@class='shopee-icon']"
