# tiktok scrape variables
main_link = "https://global.secure-wms.com/webui/login?callbackUri=https://secure-wms.com/smartui/?page=importitems&tplguid=%7b293ece64-000b-4a53-9bcf-2373f71e0b44%7d"
login_email = "//input[@id='login']"
password = "//input[@id='password']"
password_2 = "//div[@class='form-group']//input[@id='password']"
login = "//button[@class='wms-btn' or @type='submit' or @value='Login']"
inventory = "//ul[@id='verticalMenu']//li[@id='wms_Inventiry']//div//a[contains(text(),'Inventory')]"
manage_inventory = "//ul[@id='verticalMenu']//li[@id='wms_Inventiry']//ul[@class='vertical-dropdown active']//li//a[@title='Manage Inventory']"
options_dropdown_css2 = ".virtual-grid-options"
download_button_1 = "#GridManageInventoryBetamenu_mn_active > span:nth-child(1) > span:nth-child(1)"
download_button_2 = "//div[@class='k-animation-container']//ul//li[@class='k-state-default k-item ExportGrid k-state-hover']//span[contains(text(),'Export to Excel')]"
download_button_3 = "//div[@class='k-animation-container']//ul//li[@class='k-state-default k-item ExportGrid']//span[contains(text(),'Export to Excel')]"
profile = "//div[@class='user']//ul//li//a"
log_out = "//div[@class='user']//ul//li//a[contains(text(),'Sign out')]"
