# tiktok scrape variables
main_link = "https://seller-my.tiktok.com/account/login"
login_email = "//span[@id='TikTok_Ads_SSO_Login_Email_Panel_Button']"
mobile_number = "//input[@class='account-arco-input account-arco-input-size-default']"
email = "//input[@id='TikTok_Ads_SSO_Login_Email_Input']"
password = "//input[@id='TikTok_Ads_SSO_Login_Pwd_Input']"
login = "//button[@id='TikTok_Ads_SSO_Login_Btn']"
otp_input = "//input[@id='TT4B_TSV_Verify_Code_Input']"
Confirm = "//button[@id='TT4B_TSV_Verify_Submit_Btn']"
shopping_center_popup = "//div[@class='arco-popconfirm-btn']//button[@class='arco-btn arco-btn-primary arco-btn-size-mini arco-btn-shape-square']"
defected_orders_popup = "//div[@class='compass-arco-popconfirm-btn']//button[@class='compass-arco-btn compass-arco-btn-primary compass-arco-btn-size-mini compass-arco-btn-shape-square']"
notification_popup = "//div[@class='main-arco-popover-inner-content']//button[@class='main-arco-btn main-arco-btn-primary main-arco-btn-size-default main-arco-btn-shape-square main-m4b-button index__gotBtn--qDjjg']"
datepicker_popup = "//div[@class='flex flex-col items-end mt-16']//button[@class='compass-arco-btn compass-arco-btn-primary compass-arco-btn-size-default compass-arco-btn-shape-square']"
academy_popup = "//button[@class='sc-bdfBwQ hoqISq sc-dlfnbm fftpy']//button[@class='arco-btn arco-btn-primary arco-btn-size-large arco-btn-shape-square i18n-ecom-btn']"
calendar_button = "//div[@class='compass-arco-picker-suffix']//span[@class='compass-arco-picker-suffix-icon']"
month_button = "//div[@class='compass-arco-space compass-arco-space-horizontal compass-arco-space-align-center compass-m4b-date-picker-range-mode']//div[@class='compass-arco-space-item']//div[@class='compass-m4b-date-picker-range-mode-item' and contains(text(),'Month')]"
year_navigator_svg_css = ".compass-arco-icon-double-left"
year_navigator_svg_css_2 = ".compass-arco-icon-double-left > path:nth-child(1)"
export_button = "//div[@class='flex gap-8']//button[@class='zep-btn zep-btn-type-secondary zep-btn-size-middle']//span[contains(text(),'Export')]"
export_final_button_css = "div.grid:nth-child(1) > div:nth-child(2) > button:nth-child(1)"
profile_button = "//div[@class='index__container--iwSeY']//div[@class='index__nameContainer--W2iiF']//div[@class='index__name--7pWdl']//div[@class='index__content--BS+La']"
logout = "//div[@class='flex self-start pl-24 cursor-pointer text-neutral-text2 text-p3-semibold ']"