date_range_reports = "//kat-tab[@tab-id='DATE_RANGE_REPORTS']//span[contains(text(),'Date Range Reports')]"
generate_report = "//span[@id='drrGenerateReportButton']//span//input[@class='a-button-input']"
custom_range = "//input[@id='drrReportRangeTypeRadioCustom']"
# firstdate_box = "//input[@id='drrFromDate']"
# lastdate_box = "//input[@id='drrToDate']"
generate_button = "//span[@id='drrGenerateReportsGenerateButton-announce' and contains(text(),'Generate')]"
download_button = "//tbody//tr[@id='0']//td[@id='0-ddrAction']//span[@id='downloadButton']"
month_select = "//input[@id='katal-id-9']"
month_range = "//div[@class='time-range-selection-box main-page']//div[@class='time-range-selection selection-filter']//div[@class='dateRange-type-selection']//kat-label[@text='Month']/following-sibling::kat-dropdown"
year_range = "//div[@class='time-range-selection-box main-page']//div[@class='time-range-selection selection-filter']//div[@class='dateRange-type-selection']//kat-label[@text='Year']/following-sibling::kat-dropdown"
firstdate_box_wrapper_ul = "//kat-date-picker[@label='From']"
lastdate_box_wrapper_ul = "//kat-date-picker[@label='To']"
